name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Modify Manifest to remove HotReload
        uses: microsoft/variable-substitution@v1
        with:
          files: "module.json"
        env:
          flags.hotReload: false
          version: ${{ steps.get_version.outputs.version-without-v }}
          download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip
          esmodules: "[\"scripts/module.mjs\"]"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build All
        run: npm run build

      - name: Create ZIP archive
        run: zip -r ./module.zip module.json scripts/ styles/ templates/ lang/

      - name: Update Release with Files
        if: "!github.event.release.prerelease"
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json, ./module.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
